### ISSUE TITLE
S3 delay / errors logged downloading machine image

### ISSUE THREAD

**Issue by sjones4** [sjones4/eucalyptus#7]
The following errors are logged when first launching an instance with an image (i.e. image not cached):

cloud-error.log:

```
Wed Dec 6 17:18:15 2017 ERROR [ChunkedDataStream:web-services-worker-pool-0] [com.eucalyptus.storage.common.ChunkedDataStream.isEndOfInput(ChunkedDataStream.java):69] java.net.SocketTimeoutException: Read timed 
out
java.net.SocketTimeoutException: Read timed out
        at java.net.SocketInputStream.socketRead0(Native Method)
        at java.net.SocketInputStream.socketRead(SocketInputStream.java:116)
        at java.net.SocketInputStream.read(SocketInputStream.java:171)
        at java.net.SocketInputStream.read(SocketInputStream.java:141)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.fillBuffer(AbstractSessionInputBuffer.java:166)
        at org.apache.http.impl.io.SocketInputBuffer.fillBuffer(SocketInputBuffer.java:90)
        at org.apache.http.impl.io.AbstractSessionInputBuffer.read(AbstractSessionInputBuffer.java:183)
        at org.apache.http.impl.io.ContentLengthInputStream.read(ContentLengthInputStream.java:144)
        at org.apache.http.conn.EofSensorInputStream.read(EofSensorInputStream.java:121)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at com.amazonaws.util.ContentLengthValidationInputStream.read(ContentLengthValidationInputStream.java:57)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at java.io.FilterInputStream.read(FilterInputStream.java:83)
        at java.io.PushbackInputStream.read(PushbackInputStream.java:139)
        at com.eucalyptus.storage.common.ChunkedDataStream.isEndOfInput(ChunkedDataStream.java:61)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.flush(ChunkedWriteHandler.java:218)
        at org.jboss.netty.handler.stream.ChunkedWriteHandler.handleUpstream(ChunkedWriteHandler.java:132)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.channelInterestChanged(SimpleChannelUpstreamHandler.java:200)
        at org.jboss.netty.channel.SimpleChannelUpstreamHandler.handleUpstream(SimpleChannelUpstreamHandler.java:106)
        at org.jboss.netty.channel.DefaultChannelPipeline.sendUpstream(DefaultChannelPipeline.java:564)
        at org.jboss.netty.channel.DefaultChannelPipeline$DefaultChannelHandlerContext.sendUpstream(DefaultChannelPipeline.java:791)
        at org.jboss.netty.channel.SimpleChannelHandler.channelInterestChanged(SimpleChannelHandler.java:191)
        at org.jboss.netty.channel.SimpleChannelHandler.handleUpstream(SimpleChannelHandler.java:124)
        at org.jboss.netty.handler.timeout.IdleStateAwareChannelHandler.handleUpstream(IdleStateAwareChannelHandler.java:36)
```

nc.log:

```
2017-12-06 17:18:15  WARN | 2017-12-06 17:18:15,261-WARNING:DownloadImage(14734): Attempt:1/3, Part:"29". Expected Size:"10485760", Downloaded:"4210688"
```

There is also a delay in the image download.

The deployment has **_objectstorage_** and **_walrusbackend_** on the same host.

The instance launches successfully after the part download is retried.

**Comment by sjones4** [comment]
A configuration change that somewhat mitigates this issue is to increase the configured worker threads which are incorrectly set to 32 for 4.4.x:

```
euctl bootstrap.webservices.server_pool_max_threads=128
```

when there are more worker threads it is less likely that the same thread will end up handling a request across both the **_objectstorage_** and **_walrusbackend_** services.

**Comment by sjones4** [comment]
Moved to Corymbia/eucalyptus#18
